export const PeoplePickerGroupNotFound = "Group not found.";
export const PeoplePickerSearchText = "Search for users";
export const PeoplePickerItemLimitExceeded = "User limit exceeded.";
export const PeoplePickerGroupLimitExceeded = "Group limit exceeded.";
export const peoplePickerRemoveSuggestion = "Remove suggestion";
export const peoplePickerSuggestionsHeaderText = "Suggested users";
export const genericNoResultsFoundText = "No results found";
export const peoplePickerLoadingText = "Loading users...";
export const peoplePickerComponentTooltipMessage = "People Picker"; 